name: CI

on: [ push , pull_request ]

permissions:
  contents: write

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cargo Caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ~/.rustup
            target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Rust
        shell: bash
        run: |
          rustup default stable
          rustup target add x86_64-pc-windows-gnu
          rustc -vV
          cargo -vV

      - name: Build
        shell: bash
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BinaryPatch
          path: target/release/Patcher.exe
          if-no-files-found: error
          
      - name: Release
        if: ${{ github.event_name == 'push' }}
        uses: softprops/action-gh-release@v2.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Binary Patcher
          make_latest: true
          tag_name: latest-nightly
          files: target/release/Patcher.exe
